services:
  app:
    build: .
    container_name: task_manager_fastapi_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:masterkey@db:5432/task_manager_fastapi
    depends_on:
      - db
    networks:
      - task_manager_fastapi_network

  db:
    image: postgres:16
    container_name: task_manager_fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: task_manager_fastapi
    volumes:
      - task_manager_fastapi_postgres_data:/var/lib/postgresql/data
    networks:
      - task_manager_fastapi_network

volumes:
  task_manager_fastapi_postgres_data:


networks:
  task_manager_fastapi_network:
    driver: bridge
